/**
 * Ionic Library helper
 */

import "@ionic/core/css/ionic.bundle.css";
import { initialize, setAssetPath } from "@ionic/core/components";

initialize();
setAssetPath(new URL('/ionic/', window.location).toString());

// import { defineCustomElement as ion_accordion_group } from '@ionic/core/components/ion-accordion-group.js'; ion_accordion_group()
// import { defineCustomElement as ion_accordion } from '@ionic/core/components/ion-accordion.js'; ion_accordion()
// import { defineCustomElement as ion_action_sheet } from '@ionic/core/components/ion-action-sheet.js'; ion_action_sheet()
// import { defineCustomElement as ion_alert } from '@ionic/core/components/ion-alert.js'; ion_alert()
import { defineCustomElement as ion_app } from '@ionic/core/components/ion-app.js'; ion_app()
// import { defineCustomElement as ion_avatar } from '@ionic/core/components/ion-avatar.js'; ion_avatar()
import { defineCustomElement as ion_back_button } from '@ionic/core/components/ion-back-button.js'; ion_back_button()
// import { defineCustomElement as ion_backdrop } from '@ionic/core/components/ion-backdrop.js'; ion_backdrop()
import { defineCustomElement as ion_badge } from '@ionic/core/components/ion-badge.js'; ion_badge()
// import { defineCustomElement as ion_breadcrumb } from '@ionic/core/components/ion-breadcrumb.js'; ion_breadcrumb()
// import { defineCustomElement as ion_breadcrumbs } from '@ionic/core/components/ion-breadcrumbs.js'; ion_breadcrumbs()
import { defineCustomElement as ion_button } from '@ionic/core/components/ion-button.js'; ion_button()
import { defineCustomElement as ion_buttons } from '@ionic/core/components/ion-buttons.js'; ion_buttons()
// import { defineCustomElement as ion_card_content } from '@ionic/core/components/ion-card-content.js'; ion_card_content()
// import { defineCustomElement as ion_card_header } from '@ionic/core/components/ion-card-header.js'; ion_card_header()
// import { defineCustomElement as ion_card_subtitle } from '@ionic/core/components/ion-card-subtitle.js'; ion_card_subtitle()
// import { defineCustomElement as ion_card_title } from '@ionic/core/components/ion-card-title.js'; ion_card_title()
// import { defineCustomElement as ion_card } from '@ionic/core/components/ion-card.js'; ion_card()
// import { defineCustomElement as ion_checkbox } from '@ionic/core/components/ion-checkbox.js'; ion_checkbox()
import { defineCustomElement as ion_chip } from '@ionic/core/components/ion-chip.js'; ion_chip()
// import { defineCustomElement as ion_col } from '@ionic/core/components/ion-col.js'; ion_col()
import { defineCustomElement as ion_content } from '@ionic/core/components/ion-content.js'; ion_content()
// import { defineCustomElement as ion_datetime } from '@ionic/core/components/ion-datetime.js'; ion_datetime()
// import { defineCustomElement as ion_fab_button } from '@ionic/core/components/ion-fab-button.js'; ion_fab_button()
// import { defineCustomElement as ion_fab_list } from '@ionic/core/components/ion-fab-list.js'; ion_fab_list()
// import { defineCustomElement as ion_fab } from '@ionic/core/components/ion-fab.js'; ion_fab()
import { defineCustomElement as ion_footer } from '@ionic/core/components/ion-footer.js'; ion_footer()
// import { defineCustomElement as ion_grid } from '@ionic/core/components/ion-grid.js'; ion_grid()
import { defineCustomElement as ion_header } from '@ionic/core/components/ion-header.js'; ion_header()
import { defineCustomElement as ion_icon } from '@ionic/core/components/ion-icon.js'; ion_icon()
// import { defineCustomElement as ion_img } from '@ionic/core/components/ion-img.js'; ion_img()
// import { defineCustomElement as ion_infinite_scroll_content } from '@ionic/core/components/ion-infinite-scroll-content.js'; ion_infinite_scroll_content()
// import { defineCustomElement as ion_infinite_scroll } from '@ionic/core/components/ion-infinite-scroll.js'; ion_infinite_scroll()
// import { defineCustomElement as ion_input } from '@ionic/core/components/ion-input.js'; ion_input()
// import { defineCustomElement as ion_item_divider } from '@ionic/core/components/ion-item-divider.js'; ion_item_divider()
// import { defineCustomElement as ion_item_group } from '@ionic/core/components/ion-item-group.js'; ion_item_group()
// import { defineCustomElement as ion_item_option } from '@ionic/core/components/ion-item-option.js'; ion_item_option()
// import { defineCustomElement as ion_item_options } from '@ionic/core/components/ion-item-options.js'; ion_item_options()
// import { defineCustomElement as ion_item_sliding } from '@ionic/core/components/ion-item-sliding.js'; ion_item_sliding()
// import { defineCustomElement as ion_item } from '@ionic/core/components/ion-item.js'; ion_item()
import { defineCustomElement as ion_label } from '@ionic/core/components/ion-label.js'; ion_label()
// import { defineCustomElement as ion_list_header } from '@ionic/core/components/ion-list-header.js'; ion_list_header()
// import { defineCustomElement as ion_list } from '@ionic/core/components/ion-list.js'; ion_list()
// import { defineCustomElement as ion_loading } from '@ionic/core/components/ion-loading.js'; ion_loading()
// import { defineCustomElement as ion_menu_button } from '@ionic/core/components/ion-menu-button.js'; ion_menu_button()
// import { defineCustomElement as ion_menu_toggle } from '@ionic/core/components/ion-menu-toggle.js'; ion_menu_toggle()
// import { defineCustomElement as ion_menu } from '@ionic/core/components/ion-menu.js'; ion_menu()
// import { defineCustomElement as ion_modal } from '@ionic/core/components/ion-modal.js'; ion_modal()
// import { defineCustomElement as ion_nav_link } from '@ionic/core/components/ion-nav-link.js'; ion_nav_link()
// import { defineCustomElement as ion_nav } from '@ionic/core/components/ion-nav.js'; ion_nav()
// import { defineCustomElement as ion_note } from '@ionic/core/components/ion-note.js'; ion_note()
// import { defineCustomElement as ion_picker_column_internal } from '@ionic/core/components/ion-picker-column-internal.js'; ion_picker_column_internal()
// import { defineCustomElement as ion_picker_column } from '@ionic/core/components/ion-picker-column.js'; ion_picker_column()
// import { defineCustomElement as ion_picker_internal } from '@ionic/core/components/ion-picker-internal.js'; ion_picker_internal()
// import { defineCustomElement as ion_picker } from '@ionic/core/components/ion-picker.js'; ion_picker()
// import { defineCustomElement as ion_popover } from '@ionic/core/components/ion-popover.js'; ion_popover()
// import { defineCustomElement as ion_progress_bar } from '@ionic/core/components/ion-progress-bar.js'; ion_progress_bar()
// import { defineCustomElement as ion_radio_group } from '@ionic/core/components/ion-radio-group.js'; ion_radio_group()
// import { defineCustomElement as ion_radio } from '@ionic/core/components/ion-radio.js'; ion_radio()
// import { defineCustomElement as ion_range } from '@ionic/core/components/ion-range.js'; ion_range()
// import { defineCustomElement as ion_refresher_content } from '@ionic/core/components/ion-refresher-content.js'; ion_refresher_content()
// import { defineCustomElement as ion_refresher } from '@ionic/core/components/ion-refresher.js'; ion_refresher()
// import { defineCustomElement as ion_reorder_group } from '@ionic/core/components/ion-reorder-group.js'; ion_reorder_group()
// import { defineCustomElement as ion_reorder } from '@ionic/core/components/ion-reorder.js'; ion_reorder()
import { defineCustomElement as ion_ripple_effect } from '@ionic/core/components/ion-ripple-effect.js'; ion_ripple_effect()
// import { defineCustomElement as ion_route_redirect } from '@ionic/core/components/ion-route-redirect.js'; ion_route_redirect()
// import { defineCustomElement as ion_route } from '@ionic/core/components/ion-route.js'; ion_route()
// import { defineCustomElement as ion_router_link } from '@ionic/core/components/ion-router-link.js'; ion_router_link()
// import { defineCustomElement as ion_router_outlet } from '@ionic/core/components/ion-router-outlet.js'; ion_router_outlet()
// import { defineCustomElement as ion_router } from '@ionic/core/components/ion-router.js'; ion_router()
// import { defineCustomElement as ion_row } from '@ionic/core/components/ion-row.js'; ion_row()
// import { defineCustomElement as ion_searchbar } from '@ionic/core/components/ion-searchbar.js'; ion_searchbar()
// import { defineCustomElement as ion_segment_button } from '@ionic/core/components/ion-segment-button.js'; ion_segment_button()
// import { defineCustomElement as ion_segment } from '@ionic/core/components/ion-segment.js'; ion_segment()
// import { defineCustomElement as ion_select_option } from '@ionic/core/components/ion-select-option.js'; ion_select_option()
// import { defineCustomElement as ion_select_popover } from '@ionic/core/components/ion-select-popover.js'; ion_select_popover()
// import { defineCustomElement as ion_select } from '@ionic/core/components/ion-select.js'; ion_select()
// import { defineCustomElement as ion_skeleton_text } from '@ionic/core/components/ion-skeleton-text.js'; ion_skeleton_text()
// import { defineCustomElement as ion_slide } from '@ionic/core/components/ion-slide.js'; ion_slide()
// import { defineCustomElement as ion_slides } from '@ionic/core/components/ion-slides.js'; ion_slides()
// import { defineCustomElement as ion_spinner } from '@ionic/core/components/ion-spinner.js'; ion_spinner()
// import { defineCustomElement as ion_split_pane } from '@ionic/core/components/ion-split-pane.js'; ion_split_pane()
import { defineCustomElement as ion_tab_bar } from '@ionic/core/components/ion-tab-bar.js'; ion_tab_bar()
import { defineCustomElement as ion_tab_button } from '@ionic/core/components/ion-tab-button.js'; ion_tab_button()
import { defineCustomElement as ion_tab } from '@ionic/core/components/ion-tab.js'; ion_tab()
import { defineCustomElement as ion_tabs } from '@ionic/core/components/ion-tabs.js'; ion_tabs()
// import { defineCustomElement as ion_text } from '@ionic/core/components/ion-text.js'; ion_text()
// import { defineCustomElement as ion_textarea } from '@ionic/core/components/ion-textarea.js'; ion_textarea()
// import { defineCustomElement as ion_thumbnail } from '@ionic/core/components/ion-thumbnail.js'; ion_thumbnail()
// import { defineCustomElement as ion_title } from '@ionic/core/components/ion-title.js'; ion_title()
// import { defineCustomElement as ion_toast } from '@ionic/core/components/ion-toast.js'; ion_toast()
import { defineCustomElement as ion_toggle } from '@ionic/core/components/ion-toggle.js'; ion_toggle()
import { defineCustomElement as ion_toolbar } from '@ionic/core/components/ion-toolbar.js'; ion_toolbar()
// import { defineCustomElement as ion_virtual_scroll } from '@ionic/core/components/ion-virtual-scroll.js'; ion_virtual_scroll()
